import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        padding: 20,
    },
    progressSummaryWrapper: {
        backgroundColor: '#FFFFFF',
        padding: 21,
        borderTopLeftRadius: 7,
        borderTopRightRadius: 7,
        borderBottomRightRadius: 29,
        borderBottomLeftRadius: 29,
        marginBottom: 26,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 10,
    },
    summaryHeader: {
        alignSelf: 'center',
        fontSize: 22,
        color: '#333',
        fontWeight: 'bold',
    },
    progressBarWrapper: {
        marginTop: 16,
    },
    progressLabel: {
        alignItems: 'center',
        fontSize: 18,
        color: '#606060',
    },
    progressBar: {
        backgroundColor: '#f0f0f0',
        height: 20,
        borderRadius: 10,
        overflow: 'hidden',
        position: 'relative',
    },
    progressBarFilled: {
        backgroundColor: '#37B7C3',
        height: '100%',
        width: '75%',
    },
    progressBarLabel: {
        position: 'absolute',
        right: 10,
        top: '10%',
        transform: [{ translateY: -8 }],
        fontSize: 14,
        color: '#333',
    },
    categorySection: {
        marginBottom: 20,
        backgroundColor: '#f8f9fa',
        borderRadius: 13,
        padding: 10,
        alignItems: 'center',
        shadowOpacity: 0.1,
    },
    categoryHeaderContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
        paddingHorizontal: 15,
    },
    categoryHeader: {
        fontSize: 20,
        color: '#333',
        padding: 15,
        borderRadius: 15,
    },
    arrow: {
        fontSize: 20,
        color: '#333',
    },
    accountsContainer: {
        marginTop: 10,
    },
    accountCard: {
        backgroundColor: '#f8f9fa',
        padding: 20,
        borderRadius: 15,
        marginBottom: 10,
        position: 'relative',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 3,
    },
    accountHeaderBox: {
        position: 'absolute',
        top: 10,
        left: 10,
        backgroundColor: '#fff',
        paddingVertical: 5,
        paddingHorizontal: 10,
        borderRadius: 15,
        elevation: 2,
        zIndex: 1,
    },
    accountLogo: {
        marginTop: 25,
        width: 70,
        height: 70,
        alignSelf: 'center',
        marginVertical: 10,
    },
    billingInfo: {
        alignItems: 'center',
        marginBottom: 15,
    },
    accountAmount: {
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    accountDueDate: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
        marginBottom: 10,
    },
    accountButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 10,
    },
    btnPay: {
        backgroundColor: '#37B7C3',
        padding: 12,
        width: '48%',
        borderRadius: 20,
    },
    btnSchedule: {
        backgroundColor: '#071952',
        padding: 12,
        width: '48%',
        borderRadius: 20,
    },
    btnText: {
        color: '#fff',
        textAlign: 'center',
        fontSize: 16,
    },
    accountName: {
        fontWeight: 'bold',
        fontSize: 16,
    },
    dropdownContainer: {
        position: 'absolute',
        top: 10,
        right: 10,
        zIndex: 2,
    },
    moreOptions: {
        fontSize: 24,
        color: '#333',
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
        width: '80%',
        backgroundColor: '#fff',
        padding: 20,
        borderRadius: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 5,
    },
    modalTitle: {
        fontSize: 20,
        marginBottom: 15,
        textAlign: 'center',
    },
    categoryItem: {
        padding: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#ccc',
    },
    closeButton: {
        backgroundColor: 'red',
        padding: 10,
        width : '40%',
        borderRadius: 20,
        alignSelf: 'center',
        marginTop: 10,
    },
    closeButtonText: {
        color: '#fff',
        textAlign: 'center',
        fontSize: 16,
    },
    overdueText: {
        fontSize: 16,
        color: 'red',
        textAlign: 'center',
        marginBottom: 10,
        fontWeight: 'bold',
    },
    errorText: {
        fontSize: 16,
        color: 'red',
        textAlign: 'center',
        marginBottom: 10,
    },
});

export default styles;